# -----------------------------------------------------------------------------
# Local server settings
# -----------------------------------------------------------------------------
host: 0.0.0.0

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
serve_schema_org: false # Include Schema.org in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    false  # enables google analytics
enable_panelbear_analytics: false  # enables panelbear analytics
enable_google_verification: false  # enables google site verification
enable_bing_verification:   false  # enables bing site verification
